package com.stanisryz.logica.puzzle.core.word.quality

import com.stanisryz.logica.puzzle.core.model.Difficulty
import com.stanisryz.logica.puzzle.core.word.WordDifficultyEvaluator
import com.stanisryz.logica.puzzle.core.word.WordNormalization
import com.stanisryz.logica.puzzle.core.word.WordNormalizationRejection
import com.stanisryz.logica.puzzle.core.word.WordRules
import java.io.File
import java.util.Locale
import kotlin.system.exitProcess

/**
 * Offline, reproducible corpus preparation: normalize, filter to five-letter Cyrillic forms,
 * deduplicate, detect `Ё`/`Е` normalization collisions, and emit stable sorted project data.
 *
 * Never runs as part of gameplay or a normal build, and never touches the network.
 */
object WordLexiconPrepareTool {
    @JvmStatic
    fun main(args: Array<String>) {
        require(args.size == 2) { "Expected <sourceDirectory> <outputDirectory> arguments." }
        val sourceDirectory = File(args[0])
        val outputDirectory = File(args[1])

        val answerSource = readCandidates(File(sourceDirectory, ANSWERS_SOURCE_FILE))
        val guessSource = readCandidates(File(sourceDirectory, GUESSES_SOURCE_FILE))

        // One shared registry, so duplicates and Ё/Е collisions are detected across both sources.
        val registry = NormalizationRegistry()
        val answers = registry.prepare(ANSWERS_SOURCE_FILE, answerSource)
        val extraGuesses = registry.prepare(GUESSES_SOURCE_FILE, guessSource)
        // Wrong-length forms are filtered out by design; only unusable characters are a hard failure.
        val rejections = answers.rejections + extraGuesses.rejections
        if (rejections.isNotEmpty()) {
            System.err.println("Word lexicon preparation FAILED with ${rejections.size} unusable candidate(s):")
            rejections.forEach { System.err.println("  $it") }
            exitProcess(1)
        }

        val evaluator = WordDifficultyEvaluator()
        val answerWords = answers.words
        val answerDifficulties = answerWords.associateWith(evaluator::evaluateWord)
        val allowedGuesses = (answerWords + extraGuesses.words).distinct().sorted()

        outputDirectory.mkdirs()
        writeLines(
            file = File(outputDirectory, ALLOWED_GUESSES_FILE),
            header = "Generated by :puzzle-core:wordLexiconPrepare. Do not edit by hand.",
            lines = allowedGuesses,
        )
        writeLines(
            file = File(outputDirectory, ANSWERS_FILE),
            header = "Generated by :puzzle-core:wordLexiconPrepare. Do not edit by hand. Format: <word>\\t<difficulty>.",
            lines = answerWords.map { "$it\t${answerDifficulties.getValue(it).name}" },
        )

        printSummary(
            allowedGuesses = allowedGuesses,
            answerDifficulties = answerDifficulties,
            answerReport = answers,
            guessReport = extraGuesses,
            outputDirectory = outputDirectory,
        )
    }

    private fun printSummary(
        allowedGuesses: List<String>,
        answerDifficulties: Map<String, Difficulty>,
        answerReport: PreparedSource,
        guessReport: PreparedSource,
        outputDirectory: File,
    ) {
        val repeatedLetterAnswers = answerDifficulties.keys.count { it.toSet().size < it.length }
        println("Word lexicon prepared into ${outputDirectory.path}")
        println("  allowed guesses: ${allowedGuesses.size}")
        println("  answers: ${answerDifficulties.size}")
        Difficulty.entries.forEach { difficulty ->
            println("  answers ${difficulty.name}: ${answerDifficulties.values.count { it == difficulty }}")
        }
        println("  answers with repeated letters: ${repeatedLetterAnswers.ratio(answerDifficulties.size)}")
        println("  filtered by length: ${answerReport.filteredByLengthCount + guessReport.filteredByLengthCount}")
        println("  normalized Ё forms: ${answerReport.yoNormalizedCount + guessReport.yoNormalizedCount}")
        println("  duplicates removed: ${answerReport.duplicateCount + guessReport.duplicateCount}")
        println("  normalization collisions: ${answerReport.collisionCount + guessReport.collisionCount}")
    }

    private fun readCandidates(file: File): List<String> {
        require(file.isFile) { "Missing lexicon source file ${file.path}." }
        return file
            .readLines(Charsets.UTF_8)
            .map(String::trim)
            .filter { it.isNotEmpty() && !it.startsWith(COMMENT_PREFIX) }
    }

    private fun writeLines(
        file: File,
        header: String,
        lines: List<String>,
    ) {
        val content =
            buildString {
                append(COMMENT_PREFIX).append(' ').append(header).append('\n')
                lines.forEach { append(it).append('\n') }
            }
        file.writeText(content, Charsets.UTF_8)
    }

    private fun Int.ratio(total: Int): String {
        if (total == 0) return "n/a"
        return "$this/$total (${String.format(Locale.ROOT, "%.1f", this * 100.0 / total)}%)"
    }

    private const val ANSWERS_SOURCE_FILE = "answers_source.txt"
    private const val GUESSES_SOURCE_FILE = "guesses_source.txt"
    private const val ALLOWED_GUESSES_FILE = "allowed_guesses.txt"
    private const val ANSWERS_FILE = "answers.txt"
    private const val COMMENT_PREFIX = "#"
}

private data class PreparedSource(
    val words: List<String>,
    val rejections: List<String>,
    val filteredByLengthCount: Int,
    val duplicateCount: Int,
    val collisionCount: Int,
    val yoNormalizedCount: Int,
)

/** Remembers the first raw form behind every normalized word across all source files. */
private class NormalizationRegistry {
    private val firstRawForm = mutableMapOf<String, String>()

    fun prepare(
        sourceName: String,
        candidates: List<String>,
    ): PreparedSource {
        val words = mutableListOf<String>()
        val rejections = mutableListOf<String>()
        var filteredByLength = 0
        var duplicates = 0
        var collisions = 0
        var yoNormalized = 0

        candidates.forEach { raw ->
            when (val normalization = WordRules.normalize(raw)) {
                is WordNormalization.Rejected -> {
                    if (normalization.rejection == WordNormalizationRejection.WRONG_LENGTH) {
                        filteredByLength++
                    } else {
                        rejections += "$sourceName: '$raw' rejected (${normalization.describe()})"
                    }
                }
                is WordNormalization.Normalized -> {
                    val word = normalization.word
                    if (raw.any { it == YO_LOWER || it == YO_UPPER }) yoNormalized++
                    val previousRaw = firstRawForm[word]
                    when {
                        previousRaw == null -> {
                            firstRawForm[word] = raw
                            words += word
                        }
                        previousRaw.equals(raw, ignoreCase = true) -> duplicates++
                        else -> {
                            collisions++
                            println("  collision: '$raw' and '$previousRaw' both normalize to '$word'; keeping one entry")
                        }
                    }
                }
            }
        }

        return PreparedSource(
            words = words.sorted(),
            rejections = rejections,
            filteredByLengthCount = filteredByLength,
            duplicateCount = duplicates,
            collisionCount = collisions,
            yoNormalizedCount = yoNormalized,
        )
    }

    private fun WordNormalization.Rejected.describe(): String =
        when (rejection) {
            WordNormalizationRejection.EMPTY -> "empty"
            WordNormalizationRejection.WRONG_LENGTH -> "not ${WordRules.WORD_LENGTH} letters"
            WordNormalizationRejection.UNSUPPORTED_CHARACTER -> "unsupported character '$offendingCharacter'"
        }

    private companion object {
        const val YO_LOWER = 'ё'
        const val YO_UPPER = 'Ё'
    }
}
